---
# Source: flask-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-flask-app
  labels:
    helm.sh/chart: flask-app-0.1.0
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.2"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: flask-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-flask-app
  labels:
    helm.sh/chart: flask-app-0.1.0
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/instance: release-name
---
# Source: flask-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-flask-app
  labels:
    helm.sh/chart: flask-app-0.1.0
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-app
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: flask-app-0.1.0
        app.kubernetes.io/name: flask-app
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "2.2.2"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-flask-app
      securityContext:
        {}
      containers:
        - name: flask-app
          securityContext:
            {}
          image: "mohamedshokry/sampleflask:0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /products
              port: http
          readinessProbe:
            httpGet:
              path: /products
              port: http
          resources:
            {}
---
# Source: flask-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-flask-app
  labels:
    helm.sh/chart: flask-app-0.1.0
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    # - host: "52.226.58.134"
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: release-name-flask-app
                port:
                  number: 5000
---
# Source: flask-app/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-flask-app-test-connection"
  labels:
    helm.sh/chart: flask-app-0.1.0
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-flask-app:5000/products']
  restartPolicy: Never
