name: 02-AKS-Provision-Terraform
trigger:
  branches:
    include:
      - main

pool:
  name: 'local-hosted'

variables:
  terraformDirectory: 'terraform-aks-provisioning'

stages:
- stage: ProvisionAKS
  jobs:
  - job: AKSProvisioning
    displayName: 'Provision AKS Cluster using Terraform'
    steps:
    - checkout: self
      persistCredentials: true

    # Install Terraform if not available
    - script: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
        unzip terraform_1.9.8_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
      displayName: 'Install Terraform'

    # Download terraform.tfvars as a secure file if it's stored as a secret
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'terraform.tfvars'

    - script: |
        # Move terraform.tfvars into the terraform-aks-provisioning directory
        cp "$(System.DefaultWorkingDirectory)/_temp/terraform.tfvars" "$(terraformDirectory)/terraform.tfvars"
        
        # Set environment variables for ARM_* using Azure DevOps secrets
        export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
        export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
        export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
        export ARM_TENANT_ID=$(ARM_TENANT_ID)
        
        # Execute Terraform commands
        terraform -chdir=$(terraformDirectory) init
        terraform -chdir=$(terraformDirectory) plan -var-file=terraform.tfvars -out=terraform.tfplan
        terraform -chdir=$(terraformDirectory) apply -auto-approve terraform.tfplan
      displayName: 'Initialize, Plan, and Apply Terraform'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)